steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/${_DIR}:latest ${_DIR}']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/${_DIR}:latest']
   secretEnv: ['USERNAME']
availableSecrets:
   secretManager:
   - versionName: projects/$PROJECT_NUMBER/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/$PROJECT_NUMBER/secrets/docker-username/versions/1
     env: 'USERNAME'
options:
   logging: CLOUD_LOGGING_ONLY
timeout: 7200s